[run]
# Prepends $PATH with `node` executable which's a symlink to `bun`
bun = true

[install]
# Use the exact versions specified in package.json
exact = true

# Cache downloaded packages
cache = true

# Use frozen installation (equivalent to npm's --frozen-lockfile)
frozen = true

[build]
# Default entry points
entrypoints = ["src/index.ts"]

# Default target platform
target = "node"

# Default output directory
outdir = "dist"

# Default sourcemap generation
sourcemap = "inline"

# Default external dependencies
external = ["consolidate", "rollup"]
