name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Show Bun version
        run: |
          echo "Bun version: $(bun --version)"

      - name: Install Dependencies
        run: |
          bun install --frozen
        env:
          HUSKY_SKIP_INSTALL: 1
          CI: true

      - name: Test
        run: bun run test
        env:
          CI: true
