name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Show Bun version
        run: |
          echo "Bun version: $(bun --version)"

      - name: Install Dependencies
        run: |
          bun install --frozen
        env:
          HUSKY_SKIP_INSTALL: 1
          CI: true

      - name: Release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
